---
- name: Ensure Python 3 and pip are installed
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ python_packages }}"

- name: Ensure Python 3 venv is installed
  become: true
  apt:
    name: python3-venv
    state: present

- name: Install Flask and Gunicorn in virtual environment
  pip:
    name: "{{ item }}"
    virtualenv: "{{ python_app_venv_path }}"
    state: present
  with_items: "{{ python_app_packages }}"
  
- name: Create deployment directory
  file:
    path: "{{ python_app_deployment_folder }}"
    state: directory
    mode: 0755

- name: Create virtual environment
  command: python3 -m venv "{{ python_app_venv_path }}"
  args:
    chdir: "{{ python_app_deployment_folder }}"

- name: Copy application wheel file
  copy:
    src: "{{ python_app_wheel_path }}"
    dest: "{{ python_app_deployment_folder }}"
    mode: 0644

- name: Install application dependencies in virtual environment
  pip:
    name: "{{ python_app_deployment_folder }}/{{ python_app_wheel_name }}"
    virtualenv: "{{ python_app_venv_path }}"
    state: present

- name: Create instance folder for application configurations
  file:
    path: "{{ python_app_instance_folder }}"
    state: directory
    mode: 0755

- name: Deploy application configuration file
  template:
    src: "{{ python_app_config_template }}"
    dest: "{{ python_app_instance_folder }}/config.py"
    mode: 0644  

- name: Deploy run.sh script
  template:
    src: "{{ python_app_run_script_template }}"
    dest: "{{ python_app_deployment_folder }}/run.sh"
    mode: 0755

- name: Create systemd service file for the application
  template:
    src: "{{ python_app_service_template }}"
    dest: "/etc/systemd/system/{{ python_app_service_name }}.service"
    mode: 0644
  notify: 
    - Start and enable the application service

- name: Start and enable the application service
  systemd:
    name: "{{ python_app_service_name }}"
    enabled: yes
    state: started

- name: Reload systemd for changes to take effect
  systemd:
    daemon_reload: yes
